// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhiplsukisyrnyzlksxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoaXBsc3VraXN5cm55emxrc3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDAyMTAsImV4cCI6MjA3MjYxNjIxMH0.dTulBBd_ONj_GacgiyqUr8Ur1feT0xwE50fDBMH5JOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});